### ISSUE TITLE
Draft work item ignores work item type

### ISSUE THREAD

**Issue by SBI-** [jazz-community/rtc-create-child-item-plugin#1]
When creating a draft work item using OSLC, the work item type set in the `rtc_cm:type` field is always ignored, and the top most value available in the work item editor drop down is used. As this is obviously wrong, we have to look for a workaround. Two possible solutions could be:

- Setting a cookie and manipulating the new work item editor in the initialization phase of the button, setting the work item type to what was actually set in the OSLC payload.
- Use a callback to store a value that can be used the next time the button is instantiated on the new work item, and then also set the correct work item type in the editor.

Once a work around for this problem exists, creating work items with a defined type and linking with a predefined type will work as planned. Most of the UI enhancements are already implemented on the [UI Chooser Enhancement](https://github.com/jazz-community/rtc-create-child-item-plugin/tree/ui-chooser-enhancement) branch.

**Comment by joemeagher** [comment]
Is there any work around for this?  I've tried hard coding the type using dc:type, rtc_cm:type, and various other things, but nothing seems to work.  Has anyone else found a solution?

**Comment by innerjoin** [comment]
@SBI-, did you create a defect on jazz.net for this?

**Comment by innerjoin** [comment]
The upcoming 6.0.6 release of RTC will feature a create child button in the work item editor that is more advanced than this plug-in. Therefore, we can close this issue as this project will no longer be actively improved.
